OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-4o-mini"
LOCAL_LLM_URl= ""